name: SonarCloud Analysis
on:
  push:
    branches:
      - master  # Replace with your default branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for SonarCloud to analyze the full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Skipping dependency installation."
          fi

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_PROJECT_KEY: Rinub_Backend_application_Django  
          SONAR_ORGANIZATION: rinub  